### ISSUE TITLE
Enable the CSR for use in Fahrenheit.

### ISSUE THREAD

**Issue by fkelava** [peppy-enterprises/fahrenheit#4]
CSR 1.x relies on polling/memory-reading to work. In Fahrenheit, this is now moot, because @EvelynTSMG figured out a way to have code execute on every main loop iteration. The CSR should be ported by:

- Moving its execution logic into a ``LateUpdate`` hook
- Removing all memory-reading/process-injection code

**Comment by EvelynTSMG** [comment]
Update!
The CSR is being ported by no-oping instructions in event scripts using a postfix hook into the game's event loading function :3

**Comment by EvelynTSMG** [comment]
- Dream Zanarkand
  - [X] Skip Intro
  - [X] Beginning
  - [ ] Naming Tidus
  - [ ] Kids
  - [ ] Fangirls
  - [ ] Tidus leaves fans
  - [X] Tidus looks at Jecht sign
  - [X] Blitzball FMV
  - [ ] Tidus wakes up and follows Auron
  - [ ] Tidus sees the fayth and follows Auron
  - [ ] Ammes
  - [ ] Tidus sees Jecht sign again
  - [ ] Tanker
  - [ ] Tidus and Auron run as bridge explodes
  - [ ] This is your story FMV
  - [ ] Fix menu bug
  - [ ] Tidus swimming looking at himself as a child
  - [ ] A dream of being alone

- Baaj Temple
  - [ ] Tidus wakes up
  - [ ] Tidus falls in the water
  - [ ] Geosgaeno eats a Sahagin
  - [ ] Escape from Geogaesno
  - [ ] Tidus in a collapsed corridor
  - [ ] Tidus needs fire
  - [ ] Tidus makes fire
  - [ ] Tidus has a dream about Auron
  - [ ] Klikk
  - [ ] Rikku punches Tidus

- Cid's Ship
  - [ ] Tidus wakes up on boat + Sphere Grid tutorial
  - [ ] Rikku explains the mission
  - [ ] They enter the submerged ruins

- Underwater Ruins
  - [ ] Tidus bashes the machine
  - [ ] Tidus bashes the machine + Tros arrives
  - [ ] They leave the submerged ruins
  - [ ] Airship is shown
  - [ ] Tidus gets back onto the boat

- Cid's Ship
  - [ ] Naming Rikku
  - [ ] Rikku suggests going to Luca

- Besaid
  - [ ] Tidus wakes up in the sea
  - [X] Lagoon drop
  - [ ] Wakka asks Tidus to join his team
  - [ ] Wakka explains his life story
  - [ ] Tidus arrives at Besaid Village
  - [ ] Tidus enters the temple
  - [ ] Tidus speaks to the priest
  - [ ] Priest enters Wakka's tent
  - [ ] Tidus dreams about a flashback
  - [ ] Tidus goes back into the temple
  - [ ] Wakka catches up with Tidus in trials
  - [ ] Tidus meets Lulu and Kimahri + FMV 
  - [ ] The gang leave the cloister of trials
  - [ ] Naming Valefor
  - [ ] Besaid Night
  - [ ] Tidus sleeping
  - [ ] Tidus has a dream about Yuna, Tidus wakes up + FMV
  - [ ] Tidus wakes up again (Party healed at this point)
  - [ ] Yuna says goodbye to Besaid
  - [ ] Yuna says goodbye to Besaid again
  - [ ] Kimahri Intro
  - [ ] Post-Kimahri
  - [ ] S.S. Liki departs

- S.S. Liki
  - [ ] Tidus goofing around
  - [ ] Lord Braska's daughter?
  - [ ] She's the daughter of High Summoner Braska
  - [ ] Tidus talks to Yuna
  - [ ] Sin Fin
  - [ ] Echuilles
  - [ ] Recovering on the boat
  - [ ] Map shown

- Kilika
  - [ ] Undocking in Kilika
  - [ ] Sending
  - [ ] Tidus wakes up
  - [ ] Tidus speaks to Wakka
  - [ ] Camera pan + Yuna wants a new guardian
  - [ ] Race up the stairs
  - [ ] Pre-Geneaux
  - [ ] No replacement for Chappu
  - [ ] Arrival at temple
  - [ ] Camera pan in Kilika Temple
  - [ ] Pray or Stand
  - [ ] Tidus is denied access
  - [ ] Trials Entry
  - [ ] Trials Camera Pan
  - [ ] Guardians are annoyed at Tidus
  - [ ] Fayth explanation
  - [ ] Naming Ifrit
  - [ ] Exit Temple
  - [ ] Tidus misses home
  - [ ] Setting off to Luca

- S.S. Winno
  - [ ] Opening scenes
  - [ ] Meet O'aka
  - [ ] Eavesdropping on Lulu and Wakka
  - [ ] Tidus looks at the blitzball
  - [ ] Zanarkand flashback
  - [ ] Jecht Shot Failure
  - [ ] Jecht Shot Success
  - [ ] Tidus speaks to Yuna

- Luca
  - [ ] Luca FMV + Kilika Beasts undock
  - [ ] Inside the Cafe
  - [ ] Besaid Aurochs undock
  - [ ] Seymour arrives
  - [ ] Yuna enters the changing room
  - [ ] Speaking to the Al Bhed
  - [ ] Camera pan
  - [ ] Crowd mob Yuna
  - [ ] Crowd mob Yuna
  - [ ] Tidus and Yuna talk about Luca
  - [ ] Tidus and Yuna talk about Luca
  - [ ] Tidus and Yuna at the cafe
  - [ ] Mika begins the tournament
  - [ ] Al Bhed Auroch game starts
  - [ ] Kimahri Yuna's gone
  - [ ] Lulu explains the situation
  - [ ] Wakka takes a beating
  - [ ] Party jumps on the boat
  - [ ] Oblitzerator
  - [ ] Aurochs win the game
  - [ ] Wakka is injured
  - [ ] Wakka subs himself
  - [ ] Lulu speaks to Wakka
  - [ ] Pre-Blitzball
  - [ ] Halftime talk
  - [ ] Fans are getting impatient
  - [ ] Wakka chants
  - [ ] Ah! It's Wakka!
  - [ ] Aurochs win/lose the game
  - [ ] Pre-Sahagins
  - [ ] Lulu what's happening
  - [ ] Vouivre to Anima
  - [ ] Wakka quits the Aurochs
  - [ ] Wakka joins Yuna
  - [ ] Tidus shouts at Auron
  - [ ] Tidus and Auron join the group
  - [ ] HA HA HA HA

- Mi'ihen
  - [ ] Tidus runs up the stairs
  - [ ] Meet Calli
  - [ ] Luzzu, Gatta and Shelinda scenes
  - [ ] Auron is tired
  - [ ] Tidus chats with Yuna
  - [ ] Tidus chats to a guy
  - [ ] Meet Rin
  - [ ] To the chocobo corral
  - [ ] Chocobo Eater
  - [ ] Chocobo Eater loss - Fall down the cliff
  - [ ] Chocobo Eater win - Rin thanks the party
  - [ ] Luzzu and Gatta move a cart
  - [ ] Seymour helps out

- Mushroom Rock Road
  - [ ] Tidus distrusts Seymour
  - [ ] Send Clasko to the shadow realm
  - [ ] Preparing for Sin
  - [ ] Sinspawn Gui
  - [ ] Tidus wakes up
  - [ ] Tidus sees Gatta
  - [ ] Sin FMV + Tidus chases after Sin
  - [ ] Yuna tries to summon
  - [ ] Tidus is swimming
  - [ ] Nucleus
  - [ ] Zanarkand flashback
  - [ ] Tidus monologue on beach (Terra Skip)
  - [ ] Tidus monologue on beach
  - [ ] Kinoc retreats
  - [ ] Tidus speaks to Auron
  - [ ] Leaving Mushroom Rock Road"

- Djose
  - [ ] Kimahri speaks
  - [ ] Tidus is eager to go to Zanarkand
  - [ ] Tidus whoa
  - [ ] Arrival at Djose Temple
  - [ ] Meet Isaaru
  - [ ] Entering the Djose trials
  - [ ] Naming Ixion
  - [ ] Tidus wakes up
  - [ ] Tidus wakes Yuna up
  - [ ] Yuna has bed hair
  - [ ] Clasko wait for me
  - [ ] Moonflow here we come

- Moonflow
  - [ ] Biran and Yenke taunt
  - [ ] Tidus sees the Moonflow river
  - [ ] Tidus sees a shoopuf
  - [ ] The chocobos cannot cross
  - [ ] All Aboards!
  - [ ] Shoopuf launching + map
  - [ ] A sunken city
  - [ ] Debate about machina
  - [ ] Extractor
  - [ ] Back on the shoopuf
  - [ ] Reunite with Rikku + FMV
  - [ ] Map shown

- Guadosalam
  - [ ] Meet Tromell + Customise tutorial
  - [ ] Tromell invites the gang in
  - [ ] Seymour's House
  - [ ] Seymour proposes to Yuna
  - [ ] Yuna drinks a glass of water
  - [ ] The gang discuss the proposal
  - [ ] Tidus freaks out about the undead
  - [ ] Auron and Rikku stay behind
  - [ ] Tidus enters the Farplane
  - [ ] Farplane
  - [ ] Zanarkand flashback
  - [ ] Tidus is embarrassed
  - [ ] Jyscal returns
  - [ ] Tidus asks about Jyscal
  - [ ] Affection scene
  - [ ] Tidus speaks to Shelinda
  - [ ] Yuna asks Jyscal what she can do
  - [ ] Macarena Temple

- Thunder Plains
  - [ ] Map + Rikku afraid + tutorial
  - [ ] Rikku freaks out
  - [ ] Rikku asks to go to the agency
  - [ ] Tidus barges in Yuna's room + Sleep
  - [ ] Leaving the agency
  - [ ] Yuna decides to marry Seymour

- Macalania
  - [ ] Arriving at Macalania
  - [ ] Tidus is worried about Yuna
  - [ ] Barthello has lost Dona + Butterfly guy
  - [ ] Auron open ways to Spherimorph
  - [ ] Spherimorph
  - [ ] Tromell
  - [ ] Crawler
  - [ ] Jyscal Skip
  - [ ] Seymour!
  - [ ] Post-Seymour
  - [ ] Naming Shiva
  - [ ] Backflip Skip
  - [ ] Wendigo
  - [ ] Under the lake

- Bikanel
  - [ ] Bikanel
  - [ ] Wakka Glare
  - [ ] Sanubia to Home
  - [ ] Home
  - [ ] Home to Airship
  - [ ] Airship Bridge Cutscene
  - [ ] Red carpet has teeth
  - [ ] Pre-Evrae

- Bevelle
  - [ ] Evrae to Guards
  - [ ] Guards
  - [ ] Bevelle Guards to Trials
  - [ ] Trials to Bahamut naming
  - [ ] Via Purifico - Tidus side
  - [ ] Via Purifico - Yuna side
  - [ ] Isaaru
  - [ ] Evrae Altana
  - [ ] Enter Highbridge
  - [ ] Seymour Natus
  - [ ] Natus Death

- Calm Lands
  - [ ] Lake Scene
  - [ ] Calm Lands Intro
  - [ ] Father Zuke
  - [ ] Defender X
  - [ ] Calm Lands - Gorge intro

- Gagazet
  - [ ] Yuna reflects
  - [ ] Biran + Yenke
  - [ ] Ronso Singing
  - [ ] Seymour Flux
  - [ ] Fayth FMV + Tidus collapses
  - [ ] Tidus wakes up in Zanarkand
  - [ ] Tidus enters his house
  - [ ] The fayth asks Tidus to end the dream
  - [ ] The dream disintegrates
  - [ ] Tidus wakes up
  - [ ] Gagazet Cave scenes
  - [ ] Sanctuary Keeper

- Zanarkand
  - [ ] Zanarkand Campfire
  - [ ] Zanarkand Trials Begin
  - [ ] Pre-Spectral Keeper"
  - [ ] Spectral Keeper to Yunalesca
  - [ ] Pre-Yunalesca
  - [ ] Auron reveals the truth
  - [ ] Airship arrives

- Airship, Highbridge, Sin
  - [ ] Yuna/Kimahri talk about defeating Sin
  - [ ] Shelinda + Mika
  - [ ] Bahamut Fayth
  - [ ] Return from Highbridge
  - [ ] Sin destination cutscene
  - [ ] Left Fin
  - [ ] Left fin Pre-Boss
  - [ ] Right Fin Pre-Boss
  - [ ] Star Players First!
  - [ ] Sin Core
  - [ ] Yuna monologue
  - [ ] Overdrive Sin
  - [ ] Pre-Omnis
  - [ ] Enter Tower of the Dead
  - [ ] Pre-BFA
  - [ ] BFA Death
  - [ ] Contest of Aeons!

- Cavern of the Stolen Fayth
  - [ ] Lady Ginnem Attacks
  - [ ] Yojimbo Fayth Intro

- Post Battle Transitions
  - [ ] Klikk
  - [ ] Geneaux
  - [ ] Ifrit
  - [ ] Machina
  - [ ] Oblitzerator
  - [ ] Sinspawn Gui 2
  - [ ] Spherimorph
  - [ ] Crawler
  - [ ] Wendigo
  - [ ] Bikanel Zu
  - [ ] Home Bombs
  - [ ] Home Dual Horns
  - [ ] Home Chimera
  - [ ] Evrae
  - [ ] Seymour Natus
  - [ ] Defender X
  - [ ] Biran + Yenke
  - [ ] Seymour Flux
  - [ ] Sanctuary Keeper
  - [ ] Spectral Keeper to Yunalesca
  - [ ] Yunalesca
  - [ ] Left Fin
  - [ ] Right Fin
  - [ ] Sin Core
  - [ ] Seymour Omnis
  - [ ] Yojimbo

**Comment by fkelava** [comment]
See #16.

**Comment by fkelava** [comment]
Superseded by peppy-enterprises/fh-mods-csr#2. Closing.
